# Generated by Django 4.0 on 2022-05-12 22:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Descriptive tag', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_food', models.CharField(help_text='Type of food served by restaurant', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant.', max_length=250)),
                ('street_address', models.CharField(help_text='Address of the restaurant.', max_length=250)),
                ('city', models.CharField(help_text='City restaurant is located in.', max_length=100)),
                ('state', models.CharField(help_text='State of restaurant location.', max_length=2)),
                ('zip', models.CharField(help_text='Zip code of restaurant location.', max_length=5)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('avg_rating', models.FloatField(help_text='Average rating of all ratings given.', max_length=2)),
                ('tags', models.ManyToManyField(to='food_review.Tag')),
                ('type_food', models.ForeignKey(help_text='Type of food served by restaurant.', on_delete=django.db.models.deletion.CASCADE, to='food_review.typeoffood')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The comment text')),
                ('rating', models.PositiveIntegerField(help_text='The rating the reviewer has given.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time the review was created.')),
                ('date_updated', models.DateTimeField(help_text='The date and time the review was last edited', null=True)),
                ('restaurant', models.ForeignKey(help_text='The Restaurant that the review is for.', on_delete=django.db.models.deletion.CASCADE, to='food_review.restaurant')),
            ],
        ),
    ]
